### ISSUE TITLE
Environment setup

### ISSUE THREAD

**Issue by nikky4D** [adobe/Deep-Audio-Prior#1]
Hello,

Is there a requirements.txt somewhere that I can use for setup? I'm trying to understand the various requirements for the toolbox

**Comment by YapengTian** [comment]
Hi,

The main dependencies are Pytorch v1.0+, Librosa, OpenCV. Please install them and run the code. We will add a requirements.txt soon. Thanks

**Comment by dingzeyuli** [comment]
@nikky4D Please see our latest readme https://github.com/adobe/Deep-Audio-Prior#installing-dependencies on installing dependency (Thanks to @AbhishekSrikanth!).
