### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by ChrisCJou** [adobe/Deep-Audio-Prior#3]
Hello, this looks like a great project, but my system is having issues running it. More specifically, the Blind source separation part.

I'm not currently sure if this is due to my CUDA configuration/version or maybe some conflict with the PyTorch version and CUDA since I get an error upon hitting "Flag = s.optimize()".

What type of hardware did you run this on and what CUDA version were you running? Thanks!

**Comment by YapengTian** [comment]
Thanks for your interest! The CUDA version is 10.2  and Pytorch version is 1.2.0.

**Comment by ChrisCJou** [comment]
Hi and thanks for the reply. I was able to upgrade my Torch/Torchvision version and it looks like it is now working.

For people who encounter this issue in the future, here is what I had to change to get this working on my machine, ymmv.

1. Upgrade torch + torchvision to latest
2. Downgrade pillow version from 7.0.0 to 6.2.2
3. pip install scikit-video
4. Downgrade librosa from 0.7.2 to 0.6.3
