### ISSUE TITLE
Support for separation of >2 sources

### ISSUE THREAD

**Issue by jackgle** [adobe/Deep-Audio-Prior#5]
Hello, I am just wondering if this code supports separation of more than 2 sources. Thanks!

**Comment by YapengTian** [comment]
In the paper, we only explored 2-sound mixture separation. But it is easy to extend to multiple-sound separation by adding more generation and mask networks accordingly. But, it might be very challenging to blindly separate multiple sounds.

**Comment by jackgle** [comment]
Thanks! Just curious
